server:
  port: 8080
spring:
  redis:
    host: 192.168.209.137
    port: 6379
    password: 123123
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    # 设置使用数据库1，默认使用0
    database: 1
  application:
    name: reggie_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: xuan1303.
  servlet:
    multipart:
      max-file-size: 2MB
  # 配置邮箱相关属性
  mail:
    # 邮箱地址
    username: 240133295@qq.com
    # 授权码
    password: ytqzvyumzdzpbhge
    # 邮件服务器地址
    host: smtp.qq.com
    # 编码格式
    default-encoding: utf-8
    # 传输协议
    protocol: smtp
    # 开启加密验证
    properties:
      mail:
        smtl:
          ssl:
            enable: true
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
  type-aliases-package: com.joker.reggie.entity # 别名扫描包
reggie:
  path: D:\images\

